RIA-7939
hmcts/ia-case-notifications-api pull request #1008
Opened 2023-11-08 17:44 UTC by javierhmcts

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/RIA-7939

### Change description ###

fixed HO missing personalisation for NON ADA internal appeals when listing case

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [] Does this PR introduce a breaking change

2023-11-09 09:11 UTC, jamieclarkeHMCTS submitted a review, later dismissed

2023-11-09 09:29 UTC, neha-aggarw requested changes

2023-11-09 09:29 UTC, neha-aggarw commented on src/functionalTest/resources/scenarios/RIA-7939-internal-detained-non-ada-case-listed.json
> +  "description": "RIA-7939 Internal Detained non ADA case listed direction notification",
Don't remove previous reference. Add your along with the previous one. like RIA-7558 RIA7939 Internal........

2023-11-09 09:48 UTC, ThomasKKC requested changes
Can you rename the PR please?

2023-11-13 12:06 UTC, ThomasKKC approved these changes

2023-11-13 12:46 UTC, neha-aggarw approved these changes

2023-11-13 13:24 UTC, merged