RIA-8101 dlrm judge refactor
hmcts/ia-case-notifications-api pull request #1072
Opened 2024-01-25 14:58 UTC by jamieclarkeHMCTS

Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8101

Change description
Remove Leadership judge FTPA Decision event and rename Resident judge FTPA Decision event

### Checklist
- [x ] tests have been updated / new tests has been added (if needed)

2024-01-26 09:54 UTC, MiguelMartinRojas approved these changes
LGTM

2024-01-26 12:18 UTC, ThomasKKC requested changes

2024-01-26 12:18 UTC, ThomasKKC commented on src/functionalTest/resources/scenarios/RIA-1432-RIA-2974-RIA-3003-ftpa-applicant-appeal-decision-refused-respondent.json
> +      "eventId": "decideFtpaApplication",
As discussed, we can remove leadershipJudgeFtpaDecision scenarios.

2024-01-29 08:58 UTC, MiguelMartinRojas approved these changes

2024-01-30 10:04 UTC, ThomasKKC approved these changes

2024-01-30 11:28 UTC, merged