RIA-8184 decide_ftpa_31_32
hmcts/ia-case-notifications-api pull request #1085
Opened 2024-02-07 17:14 UTC by ikirsanov

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8184

### Change description ###
Added DECIDE_FTPA_APPLICATION under rules 31 and 32 notification and sms sending. Added junit and FT tests.

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-02-07 18:15 UTC, jamieclarkeHMCTS approved these changes

2024-02-08 12:02 UTC, jamieclarkeHMCTS submitted a review, later dismissed

2024-02-08 12:21 UTC, ThomasKKC requested changes

2024-02-08 12:21 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
> +        boolean appellantDecisionOutcomeIsRule31Or32 = asylumCase
I think we need to check the latest data from 'ftpaApplicantType' field to see which outcome type field to read from. 'RESPONDENT' or 'APPELLANT'

2024-02-08 13:13 UTC, ThomasKKC approved these changes

2024-02-08 13:30 UTC, ThomasKKC approved these changes

2024-02-08 13:58 UTC, colmlynch60 approved these changes
LGTM

2024-02-08 13:58 UTC, merged