RIA-8243 Update Tribunal Decision R31 Notification
hmcts/ia-case-notifications-api pull request #1105
Opened 2024-03-01 15:01 UTC by javierhmcts

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/RIA-8243

### Change description ###

Update Tribunal Decision R31 Notification

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-03-01 15:37 UTC, ThomasKKC requested changes

2024-03-01 15:37 UTC, ThomasKKC commented on src/main/resources/application.yaml
> +            email: da39849d-58cd-4e91-ab79-ea3083acd753
We don't need to show Listing reference anymore, so we don't need templates here

2024-03-01 15:37 UTC, ThomasKKC commented on src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
> +                            && isDlrmSetAsideEnabled(asylumCase)
Don't need this check, as the event is new.
Can you also add !AIP journey? Make sure we don't send this during AIP journey.

2024-03-01 15:37 UTC, ThomasKKC commented on src/functionalTest/resources/scenarios/RIA-8243-update-tribunal-decision-r31-notification.json
> +        "replacements": {
You sure this work? there is no "updateTribunalDecisionList": "underRule31" ?

2024-03-01 15:37 UTC, ThomasKKC commented on src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateTribunalDecisionRule31PersonalisationEmailTest.java
> +        DynamicList dynamicList = new DynamicList(new Value("allowed", "Yes, change decision to Dismissed"),
I think these values are incorrect, please check UpdateTribunalDecisionRule31MidEvent in ia-case-api

2024-03-04 14:28 UTC, MiguelMartinRojas commented on src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
> +                            && callback.getEvent() == Event.UPDATE_TRIBUNAL_DECISION
Is this a brand new event?

2024-03-04 15:13 UTC, ThomasKKC approved these changes

2024-03-04 15:22 UTC, MiguelMartinRojas approved these changes

2024-03-05 10:22 UTC, merged