Ria 5214 send notifications for application ended
hmcts/ia-case-notifications-api pull request #634
Opened 2022-05-16 11:18 UTC by Marcellofabbri

### JIRA link (if applicable) ###
[RIA-5214](https://tools.hmcts.net/jira/browse/RIA-5214)

### Change description ###
Send notifications when the application is ended to:
- applicant (sms)
- home office (email)
- legal representative if present (email)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-17 14:47 UTC, neha-aggarw requested changes

2022-05-17 15:55 UTC, Marcellofabbri commented on src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/BaseNotificationPersonalisation.java
> +    default String formatEndApplicationOutcome(String endApplicationOutcome) {
Do you know when those changes will be available?

2022-05-17 15:58 UTC, neha-aggarw commented on src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/BaseNotificationPersonalisation.java
> +    default String formatEndApplicationOutcome(String endApplicationOutcome) {
I am not sure of it. You can make the similar changes locally, and see if your document generation works. It doesn't need to be blocked till Ryan's change. Or you can check with him on the timeline.

2022-05-18 11:14 UTC, ThomasKKC approved these changes

2022-05-19 09:54 UTC, neha-aggarw approved these changes

2022-05-19 09:55 UTC, merged